// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	user "auth/app/auth/internal/handler/user"
	"auth/app/auth/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/users",
				Handler: user.CreateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/users",
				Handler: user.ListUsersHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/users/:id",
				Handler: user.UpdateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/users/:id",
				Handler: user.GetUserHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/users/:id",
				Handler: user.DeleteUserHandler(serverCtx),
			},
		},
		rest.WithPrefix("/auth/api/v1/user"),
	)
}
