// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type CreateUserReq struct {
	Username string  `json:"username"`
	Password string  `json:"password"`
	Nickname string  `json:"nickname,optional"`
	Email    string  `json:"email,optional"`
	Phone    string  `json:"phone,optional"`
	RoleIds  []int64 `json:"roleIds,optional"`
}

type IDRequest struct {
	ID int `json:"id"` // ID
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token    string   `json:"token"`
	UserId   int64    `json:"userId"`
	Username string   `json:"username"`
	Nickname string   `json:"nickname"`
	Roles    []string `json:"roles"`
}

type PageJsonRequest struct {
	Current  int32 `json:"current"`   // 当前页
	PageSize int32 `json:"page_size"` // 每页大小
}

type PageRequest struct {
	Current  int32 `json:"current"`   // 当前页
	PageSize int32 `json:"page_size"` // 每页大小
}

type PageResponse struct {
	Total           int32 `json:"total"`             // 总数
	PageSize        int32 `json:"page_size"`         // 当前页大小
	RequestPageSize int32 `json:"request_page_size"` // 请求页大小
	Current         int32 `json:"current"`           // 当前页
}

type TimeRange struct {
	StartTime string `form:"start_time,optional"` // 开始时间
	EndTime   string `form:"end_time,optional"`   // 结束时间
}

type UpdateUserReq struct {
	Id       int64   `path:"id"`
	Nickname string  `json:"nickname,optional"`
	Email    string  `json:"email,optional"`
	Phone    string  `json:"phone,optional"`
	Status   int8    `json:"status,optional"`
	RoleIds  []int64 `json:"roleIds,optional"`
}

type UserInfo struct {
	Id       int64    `json:"id"`
	Username string   `json:"username"`
	Nickname string   `json:"nickname"`
	Email    string   `json:"email"`
	Phone    string   `json:"phone"`
	Status   int8     `json:"status"`
	Roles    []string `json:"roles"`
}

type UserListReq struct {
	Page     int    `form:"page,default=1"`
	PageSize int    `form:"pageSize,default=20"`
	Username string `form:"username,optional"`
	Status   int8   `form:"status,optional"`
}

type UserListResp struct {
	Total int64      `json:"total"`
	List  []UserInfo `json:"list"`
}
